### ISSUE TITLE
Feature request: Make spruce binary work in Alpine 3.3+

### ISSUE THREAD

**Issue by mtekel** [geofffranks/spruce#128]
Still requires glibc:
```
/ # spruce
ash: spruce: not found
/ # which spruce
/usr/local/bin/spruce
/ # ls -l /usr/local/bin/spruce
-rwxr-xr-x    1 root     root       9304360 Jun  3 17:00 /usr/local/bin/spruce
/ # /usr/local/bin/spruce
ash: /usr/local/bin/spruce: not found
```

After adding https://github.com/sgerrand/alpine-pkg-glibc it starts to work as expected...
```
/ # spruce -v
spruce - Version 1.4.2
```

**Comment by dcarley** [comment]
It looks like it worked in v1.1.0 because `CGO_ENABLED=0` was added in 8c2cecaeb41386a109b5577062f31d5fefebb09b but stopped working in v1.2.0 because it was removed in f33dcd610335b56279378f8b662d5b9d4f62e07d.

Could you add that environment variable back to the build process? Could you also test in your pipeline that the Linux binary is statically linked or is executable on Alpine Linux?

**Comment by geofffranks** [comment]
This should be fixed as of 1.4.4. Can you take a look?

**Comment by dcarley** [comment]
Thanks for the quick response!

I'm still seeing a dynamically linked library for v1.4.4:
```
root@9a4ccd2d984f:/# ./spruce-linux-amd64 -v
./spruce-linux-amd64 - Version 1.4.4
root@9a4ccd2d984f:/# file spruce-linux-amd64
spruce-linux-amd64: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), not stripped
root@9a4ccd2d984f:/# ldd spruce-linux-amd64
        linux-vdso.so.1 =>  (0x00007fff63bd4000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f07699d9000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0769614000)
        /lib64/ld-linux-x86-64.so.2 (0x000056388ed30000)
```

**Comment by dcarley** [comment]
Should `force_static_binary` be `true`?

https://github.com/geofffranks/spruce/blob/967255c9142eb5de6ff170a77454cf0948e9cdac/ci/pipeline.yml#L27

**Comment by geofffranks** [comment]
Partly that, partly bad tests. 1.4.5 shows this for me:

```root@34d451c1f435:/# file spruce-linux-amd64
spruce-linux-amd64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
root@34d451c1f435:/# ldd spruce-linux-amd64
	not a dynamic executable```

**Comment by mtekel** [comment]
I can confirm this works in alpine 3.4. Resulting container size is 14MB.

Thanks!
